### ISSUE TITLE
关于前台图片替换的问题

### ISSUE THREAD

**Issue by regsinnovation** [regs-innovation/FreeManualInput#4]
如何将图片替换为新的src？ 图片中的src已经被ajax的返回值替换准确，但图片显示还是原来的内容。

**Comment by geo-will** [comment]
[desktop.zip](https://github.com/regs-innovation/FreeManualInput/files/3903553/desktop.zip)
下载附件,运行index.html,查看切换src效果;
index.html源码有实现逻辑

**Comment by regsinnovation** [comment]
Great!Thanks
